In [1]:
import pandas as pd
import numpy as np

In [2]:
CORPUS = pd.read_csv("data/CORPUS.csv", index_col=['mag_id','page_num','token_num'])
CORPUS

                           pos pos_group token_str  term_str
mag_id page_num token_num
0      1        0           DT        DT       The       the
                1           NN        NN      text      text
                2           IN        IN        on        on
                3           DT        DT      this      this
                4           NN        NN      page      page
...                        ...       ...       ...       ...
9      68       55         NNP        NN      INC.       inc
                57         NNP        NN  Michigan  michigan
                58         NNP        NN    Avenue    avenue
                60         NNP        NN   Chicago   chicago
                62         NNP        NN  Illinois  illinois

[131948 rows x 4 columns]

In [3]:
BAG = ['mag_id']
BAG

['mag_id']

In [4]:
BOW = CORPUS.groupby(BAG + ["term_str"]).term_str.count().to_frame("n")
BOW

                    n
mag_id term_str
0      abandonment  1
       abc          1
       abctv        4
       ability      3
       able         4
...                ..
9      zanzi        1
       zealand      1
       zion         1
       zone         2
       zurich       1

[39538 rows x 1 columns]

In [5]:
BOW.shape[0]

39538

In [8]:
D = BOW.groupby(BAG).n.sum()
BOW["tf"] = BOW["n"] / D

N = BOW.groupby(BAG).ngroups
DF = BOW.groupby("term_str")["n"].count()
IDF = np.log2(N / DF)

BOW["idf"] = BOW.index.get_level_values("term_str").map(IDF)
BOW["tfidf"] = BOW["tf"] * BOW["idf"]

BOW

                    n        tf       idf     tfidf
mag_id term_str
0      abandonment  1  0.000064  3.321928  0.000212
       abc          1  0.000064  1.000000  0.000064
       abctv        4  0.000255  0.321928  0.000082
       ability      3  0.000191  1.000000  0.000191
       able         4  0.000255  0.736966  0.000188
...                ..       ...       ...       ...
9      zanzi        1  0.000082  3.321928  0.000274
       zealand      1  0.000082  3.321928  0.000274
       zion         1  0.000082  1.321928  0.000109
       zone         2  0.000165  1.321928  0.000218
       zurich       1  0.000082  1.321928  0.000109

[39538 rows x 4 columns]

In [9]:
BOW.to_csv('BOW.csv')