In [64]:
import pandas as pd
import numpy as np
import plotly.express as px

from sklearn.decomposition import PCA

In [65]:
TFIDF_L2 = pd.read_csv('TFIDF_L2.csv', index_col='mag_id')
TFIDF_L2

,blacks,negroes,tito,mink,granada,diggs,ali,benson,ruby,reggie,...,moneta,sleet,oldest,sutton,basil,photos,perhaps,maurice,fentress,confidential
mag_id,,,,,,,,,,,,,,,,,,,,,
0,0.299832,0.000000,0.000000,0.000000,0.000000,0.018145,0.049899,0.000000,0.000000,0.000000,...,0.001379,0.001379,0.000690,0.000690,0.001379,0.000690,0.000690,0.000690,0.000690,0.000690
1,0.000000,0.059798,0.000000,0.000000,0.000000,0.249848,0.052294,0.000000,0.000000,0.000000,...,0.000883,0.000883,0.000883,0.000883,0.001766,0.000883,0.000000,0.000883,0.000883,0.000883
2,0.089170,0.000000,0.281924,0.000000,0.268895,0.000000,0.067455,0.005945,0.000000,0.000000,...,0.000684,0.000684,0.000000,0.001367,0.000684,0.000684,0.001367,0.000684,0.000684,0.000684
3,0.106139,0.002582,0.000000,0.000000,0.000000,0.000000,0.035127,0.019901,0.019901,0.209734,...,0.000763,0.000763,0.000763,0.000763,0.000763,0.000763,0.001526,0.000763,0.000763,0.000763
4,0.079359,0.000000,0.000000,0.000000,0.000000,0.015008,0.075041,0.251304,0.006613,0.023232,...,0.002281,0.002281,0.000760,0.000760,0.000760,0.001521,0.000760,0.000760,0.000760,0.000760
5,0.000000,0.083483,0.000000,0.264723,0.000000,0.000000,0.000000,0.000000,0.012998,0.000000,...,0.000000,0.000000,0.001495,0.000000,0.000000,0.000747,0.000747,0.000747,0.000000,0.000000
6,0.000000,0.058463,0.000000,0.000000,0.000000,0.005980,0.000000,0.000000,0.000000,0.000000,...,0.000909,0.000909,0.000909,0.000909,0.000909,0.000000,0.000909,0.000909,0.000909,0.000909
7,0.000000,0.036335,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.217804,0.000000,...,0.000894,0.000894,0.001789,0.001789,0.000894,0.000894,0.000894,0.000000,0.000894,0.000894
8,0.000000,0.084661,0.000000,0.010206,0.000000,0.005876,0.000000,0.007768,0.000000,0.000000,...,0.000893,0.000893,0.000893,0.000893,0.000893,0.000893,0.000893,0.000893,0.000893,0.000893
9,0.000000,0.033191,0.013615,0.010185,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000891,0.000891,0.000891,0.000891,0.000891,0.001783,0.000891,0.001783,0.000891,0.000891

In [66]:
pca_engine = PCA(n_components=10, random_state=42)

DCM = pd.DataFrame(pca_engine.fit_transform(TFIDF_L2),
                   index=TFIDF_L2.index)

DCM.columns = [f"PC{i}" for i in range(10)]
DCM

,PC0,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9
mag_id,,,,,,,,,,
0,0.360556,0.033542,0.096010,0.384157,0.180464,0.192301,-0.414893,0.525665,0.136259,3.120312e-14
1,0.063315,-0.503671,0.566609,-0.101797,0.406811,-0.103454,0.207536,-0.106894,-0.107546,3.120312e-14
2,0.336843,0.410416,-0.131585,0.430800,0.114513,-0.291985,0.434789,-0.221630,-0.117828,3.120312e-14
3,0.433394,-0.034803,-0.148886,-0.312466,-0.219904,0.243574,-0.244226,-0.223310,-0.549857,3.120312e-14
4,0.376058,-0.146926,-0.160420,-0.348699,-0.241375,-0.084428,0.133133,-0.054756,0.650071,3.120312e-14
5,-0.273172,0.622589,0.519122,-0.275388,-0.148021,0.110097,-0.029458,0.019312,0.072520,3.120312e-14
6,-0.362150,-0.190189,-0.001442,0.444005,-0.191885,0.193293,-0.271835,-0.529410,0.186035,3.120312e-14
7,-0.336593,0.003598,-0.404322,-0.122949,0.339222,0.530264,0.349153,0.147606,-0.001706,3.120312e-14
8,-0.286845,-0.256191,-0.019037,0.128097,-0.559910,-0.227581,0.231046,0.430743,-0.228895,3.120312e-14
9,-0.311405,0.061635,-0.316050,-0.225759,0.320084,-0.562080,-0.395245,0.012674,-0.039054,3.120312e-14

In [67]:
COMPS = pd.DataFrame(pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_), index=TFIDF_L2.columns)

COMPS.columns = [f"PC{i}" for i in range(10)]
COMPS.index.name = "term_str"

COMPS.T

term_str,blacks,negroes,tito,mink,granada,diggs,ali,benson,ruby,reggie,...,moneta,sleet,oldest,sutton,basil,photos,perhaps,maurice,fentress,confidential
PC0,6.879402e-02,-2.762323e-02,2.916684e-02,-2.520923e-02,2.911895e-02,7.765338e-03,2.811985e-02,3.308245e-02,-2.113794e-02,3.203112e-02,...,2.597266e-04,2.597266e-04,-3.061375e-04,-2.683515e-05,9.383458e-05,3.882896e-05,9.262641e-05,-6.214124e-05,-4.069369e-06,-4.069369e-06
PC1,1.076527e-02,-3.048794e-03,4.008438e-02,5.600225e-02,3.795657e-02,-4.473958e-02,-3.174119e-03,-1.278278e-02,2.480386e-03,-3.684507e-03,...,-2.831673e-04,-2.831673e-04,1.038944e-05,-1.166719e-04,-3.593112e-04,-1.432437e-05,1.861088e-04,-3.646004e-05,-2.142674e-04,-2.142674e-04
PC2,-3.970813e-03,1.728027e-02,-1.431998e-02,4.635325e-02,-1.223854e-02,4.869486e-02,2.862922e-03,-1.529098e-02,-2.951831e-02,-1.209010e-02,...,-2.069482e-04,-2.069482e-04,2.893376e-05,-3.016583e-04,5.053691e-05,-1.504518e-04,-2.547611e-04,1.637956e-05,-1.454570e-04,-1.454570e-04
PC3,3.226741e-02,-1.754076e-03,4.117936e-02,-2.570459e-02,4.029606e-02,-7.057716e-03,2.004477e-03,-3.140890e-02,-1.352575e-02,-2.561484e-02,...,-3.224629e-05,-3.224629e-05,-2.237782e-04,1.242697e-04,1.209567e-04,-3.141214e-04,3.930161e-05,-4.324238e-05,6.008825e-05,6.008825e-05
PC4,7.636323e-03,-8.491994e-03,1.282099e-02,-1.456952e-02,1.077406e-02,3.388973e-02,4.256684e-03,-2.403921e-02,2.308902e-02,-1.809990e-02,...,-4.119488e-05,-4.119488e-05,4.508070e-05,1.772663e-04,2.129704e-04,1.016352e-04,-1.520121e-04,-1.331827e-06,4.371282e-05,4.371282e-05
PC5,1.786217e-02,-1.309204e-03,-3.165143e-02,7.422042e-03,-2.762080e-02,-8.375274e-03,-4.675253e-03,-6.991367e-03,4.264275e-02,1.728177e-02,...,-3.055426e-05,-3.055426e-05,2.629276e-04,6.461086e-05,-1.752625e-05,-2.637254e-04,2.420599e-05,-3.461867e-04,-3.202934e-05,-3.202934e-05
PC6,-3.572346e-02,4.441987e-03,4.145839e-02,-3.348496e-03,4.135806e-02,1.629187e-02,7.389886e-03,1.166526e-02,2.535842e-02,-1.702589e-02,...,-1.943709e-05,-1.943709e-05,-9.663205e-08,2.257493e-04,-2.622224e-05,9.461335e-07,-2.325613e-05,-2.327479e-04,1.013781e-05,1.013781e-05
PC7,3.906336e-02,2.114662e-03,-2.216780e-02,3.428801e-03,-2.120186e-02,-6.626302e-03,-2.228117e-03,-5.754943e-03,9.817026e-03,-1.711508e-02,...,8.204461e-05,8.204461e-05,9.385643e-05,-2.420614e-05,7.808412e-05,1.482535e-04,-9.305430e-05,-5.509620e-05,-1.727941e-05,-1.727941e-05
PC8,8.460713e-03,-4.183443e-03,-1.211197e-02,5.908386e-03,-1.137020e-02,-5.337839e-03,8.144306e-03,5.381071e-02,-2.179288e-03,-3.596646e-02,...,3.604087e-04,3.604087e-04,3.913964e-05,-5.756558e-05,-2.848387e-05,9.556261e-05,-1.539996e-04,-2.060971e-05,-2.811394e-05,-2.811394e-05
PC9,-1.146308e-14,4.330552e-16,2.770009e-15,1.689895e-14,1.266010e-14,9.687525e-15,1.584082e-14,6.268390e-15,7.643111e-15,4.183326e-16,...,5.005497e-18,5.005497e-18,-2.078022e-19,2.037612e-19,4.263956e-18,-4.692508e-19,1.384230e-18,1.658213e-18,3.066050e-18,3.066050e-18

In [68]:
PC0 = COMPS["PC0"].sort_values(ascending=False).head(5).to_frame("PC0")
PC0

               PC0
term_str
blacks    0.068794
benson    0.033082
reggie    0.032031
tito      0.029167
granada   0.029119

In [69]:
PC1 = COMPS["PC1"].sort_values().head(5).to_frame("PC1")
PC1

               PC1
term_str
diggs    -0.044740
bavasi   -0.040124
wills    -0.024033
tornado  -0.023406
edt      -0.018926

In [70]:
# data for plotting
LIB = pd.read_csv('data/LIB.csv', index_col=['mag_id'])
LIB

,epub_id,date,pages,month,quarter,page_num,character_len
mag_id,,,,,,,
0,vo8DAAAAMBAJ,1972-12-07,"[""\n\n\n\nThis book was produced in EPUB forma...",12,4th Quarter,68,99374
1,ProDAAAAMBAJ,1967-05-11,"[""\n\n\n\nThis book was produced in EPUB forma...",5,2nd Quarter,68,74986
2,dEIDAAAAMBAJ,1975-11-20,"[""\n\n\n\nThis book was produced in EPUB forma...",11,4th Quarter,68,89009
3,YEIDAAAAMBAJ,1978-05-04,"[""\n\n\n\nThis book was produced in EPUB forma...",5,2nd Quarter,68,85341
4,AMADAAAAMBAJ,1978-07-06,"[""\n\n\n\nThis book was produced in EPUB forma...",7,3rd Quarter,68,89396
5,JEMDAAAAMBAJ,1951-11-01,"[""\n\n\n\nThis book was produced in EPUB forma...",11,4th Quarter,68,81741
6,vq8DAAAAMBAJ,1960-03-10,"[""\n\n\n\nThis book was produced in EPUB forma...",3,1st Quarter,68,79252
7,fbcDAAAAMBAJ,1958-02-20,"[""\n\n\n\nThis book was produced in EPUB forma...",2,1st Quarter,68,74909
8,YkEDAAAAMBAJ,1959-08-20,"[""\n\n\n\nThis book was produced in EPUB forma...",8,3rd Quarter,68,78302
9,mEEDAAAAMBAJ,1959-04-09,"[""\n\n\n\nThis book was produced in EPUB forma...",4,2nd Quarter,68,76401

In [71]:
# Plot 1: documents in PCA space
DCM_META = DCM.join(LIB[['quarter']])

px.scatter(DCM_META.reset_index(),
           x="PC0",
           y="PC1",
           color="quarter",
           hover_name="mag_id",
           title="PCA Document Scatterplot by Quarter",
           height=400,
           width=600)

In [72]:
# loadings scatterplot 
LOADINGS = COMPS[["PC0", "PC1"]].reset_index()

px.scatter(LOADINGS,
           x="PC0",
           y="PC1",
           text="term_str",
           title="PCA Loadings Scatterplot",
           height=500,
           width=700)

### PCA VISUALIZATION 1
- The first component shows a clear split in vocabulary, separating documents based on different themes or types of language.

In [73]:
px.scatter(DCM_META.reset_index(),
           x="PC2",
           y="PC3",
           color="quarter",
           hover_name="mag_id",
           title="PCA Document Scatterplot by Quarter: PC2 vs PC3",
           height=500,
           width=700)

In [74]:
LOADINGS_23 = COMPS[["PC2", "PC3"]].reset_index()

px.scatter(LOADINGS_23,
           x="PC2",
           y="PC3",
           hover_name="term_str",
           title="PCA Loadings Scatterplot: PC2 vs PC3",
           height=500,
           width=700)

### PCA VISUALIZATION 2
- The second component shows a more subtle split in vocabulary. It’s not as strong as the first, but it still separates documents based on smaller differences in language and themes.

In [75]:
DCM.to_csv("PCA_DCM.csv")
COMPS.to_csv("PCA_COMPS.csv")