In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from IPython.display import display, HTML

#### SENTIMENT VOCAB

In [3]:
# load vocab
VOCAB = pd.read_csv("data/VOCAB.csv", index_col="term_str")
VOCAB

,n,n_chars,p,i,max_pos,max_pos_group,stop,stem_porter
term_str,,,,,,,,
aa,2,2,0.000015,16.009610,NNP,NN,0,aa
aaf,1,3,0.000008,17.009610,NNP,NN,0,aaf
aaron,11,5,0.000083,13.550178,NNP,NN,0,aaron
ababa,1,5,0.000008,17.009610,NNP,NN,0,ababa
abandoned,2,9,0.000015,16.009610,VBN,VB,0,abandon
...,...,...,...,...,...,...,...,...
zumwalt,1,7,0.000008,17.009610,NNP,NN,0,zumwalt
zunicia,1,7,0.000008,17.009610,NNP,NN,0,zunicia
zuniga,2,6,0.000015,16.009610,NNP,NN,0,zuniga
zurich,5,6,0.000038,14.687682,NNP,NN,0,zurich
zw,1,2,0.000008,17.009610,NN,NN,0,zw

In [9]:
# load sentiment lexicon
SALEX = pd.read_csv("lexicons/salex_nrc.csv").set_index('term_str')
SALEX.columns = [col.replace('nrc_','') for col in SALEX.columns]
SALEX

,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust,sentiment
term_str,,,,,,,,,,,
abandon,0,0,0,1,0,1,0,1,0,0,-1
abandoned,1,0,0,1,0,1,0,1,0,0,-1
abandonment,1,0,0,1,0,1,0,1,1,0,-1
abduction,0,0,0,1,0,1,0,1,1,0,-1
aberration,0,0,1,0,0,1,0,0,0,0,-1
...,...,...,...,...,...,...,...,...,...,...,...
young,0,1,0,0,1,0,1,0,1,0,1
youth,1,1,0,1,1,0,1,0,1,0,1
zeal,0,1,0,0,1,0,1,0,1,1,1
zealous,0,0,0,0,1,0,1,0,0,1,1
zest,0,1,0,0,1,0,1,0,0,1,1

In [ ]:
# load LIB + CORPUS  as TOKENS
LIB = pd.read_csv("data/LIB.csv", index_col="mag_id").sort_index()

TOKENS = pd.read_csv(
    "data/CORPUS.csv",
    index_col=["mag_id", "page_num", "token_num"]).sort_index()

TOKENS = TOKENS.join(LIB)
TOKENS

                           pos pos_group token_str  term_str       epub_id  \
mag_id page_num token_num
0      1        0           DT        DT       The       the  vo8DAAAAMBAJ
                1           NN        NN      text      text  vo8DAAAAMBAJ
                2           IN        IN        on        on  vo8DAAAAMBAJ
                3           DT        DT      this      this  vo8DAAAAMBAJ
                4           NN        NN      page      page  vo8DAAAAMBAJ
...                        ...       ...       ...       ...           ...
9      68       55         NNP        NN      INC.       inc  mEEDAAAAMBAJ
                57         NNP        NN  Michigan  michigan  mEEDAAAAMBAJ
                58         NNP        NN    Avenue    avenue  mEEDAAAAMBAJ
                60         NNP        NN   Chicago   chicago  mEEDAAAAMBAJ
                62         NNP        NN  Illinois  illinois  mEEDAAAAMBAJ

                                 date  \
mag_id page_num token_num
0      1        0          1972-12-07
                1          1972-12-07
                2          1972-12-07
                3          1972-12-07
                4          1972-12-07
...                               ...
9      68       55         1959-04-09
                57         1959-04-09
                58         1959-04-09
                60         1959-04-09
                62         1959-04-09

                                                                       pages  \
mag_id page_num token_num
0      1        0          ["\n\n\n\nThis book was produced in EPUB forma...
                1          ["\n\n\n\nThis book was produced in EPUB forma...
                2          ["\n\n\n\nThis book was produced in EPUB forma...
                3          ["\n\n\n\nThis book was produced in EPUB forma...
                4          ["\n\n\n\nThis book was produced in EPUB forma...
...                                                                      ...
9      68       55         ["\n\n\n\nThis book was produced in EPUB forma...
                57         ["\n\n\n\nThis book was produced in EPUB forma...
                58         ["\n\n\n\nThis book was produced in EPUB forma...
                60         ["\n\n\n\nThis book was produced in EPUB forma...
                62         ["\n\n\n\nThis book was produced in EPUB forma...

                           month      quarter  page_num  character_len
mag_id page_num token_num
0      1        0             12  4th Quarter        68          99374
                1             12  4th Quarter        68          99374
                2             12  4th Quarter        68          99374
                3             12  4th Quarter        68          99374
                4             12  4th Quarter        68          99374
...                          ...          ...       ...            ...
9      68       55             4  2nd Quarter        68          76401
                57             4  2nd Quarter        68          76401
                58             4  2nd Quarter        68          76401
                60             4  2nd Quarter        68          76401
                62             4  2nd Quarter        68          76401

[131948 rows x 11 columns]

In [ ]:
# join VOCAB + SALEX
VOCAB_SENT = VOCAB.join(SALEX, how="inner")
VOCAB_SENT

,n,n_chars,p,i,max_pos,max_pos_group,stop,stem_porter,anger,anticipation,disgust,fear,joy,negative,positive,sadness,surprise,trust,sentiment
term_str,,,,,,,,,,,,,,,,,,,
abandoned,2,9,0.000015,16.009610,VBN,VB,0,abandon,1,0,0,1,0,1,0,1,0,0,-1
abandonment,1,11,0.000008,17.009610,NN,NN,0,abandon,1,0,0,1,0,1,0,1,1,0,-1
abortion,5,8,0.000038,14.687682,NN,NN,0,abort,0,0,1,1,0,1,0,1,0,0,-1
absence,6,7,0.000045,14.424647,NN,NN,0,absenc,0,0,0,1,0,1,0,1,0,0,-1
absentee,1,8,0.000008,17.009610,NN,NN,0,absente,0,0,0,0,0,1,0,1,0,0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wound,4,5,0.000030,15.009610,NN,NN,0,wound,1,0,0,1,0,1,0,1,0,0,-1
wreck,1,5,0.000008,17.009610,NNP,NN,0,wreck,1,0,1,1,0,1,0,1,1,0,-1
wrongdoing,1,10,0.000008,17.009610,NN,NN,0,wrongdo,1,0,1,0,0,1,0,1,0,0,-1
young,85,5,0.000644,10.600219,JJ,JJ,0,young,0,1,0,0,1,0,1,0,1,0,1
youth,28,5,0.000212,12.202255,NN,NN,0,youth,1,1,0,1,1,0,1,0,1,0,1

In [ ]:
# check shape
VOCAB_SENT.shape

(1481, 19)

In [ ]:
# save
VOCAB_SENT.to_csv("VOCAB_SENT.csv")

### SENTIMENT BOW

In [25]:
BOW = pd.read_csv("BOW.csv", index_col=["mag_id", "term_str"])
VOCAB_SENT = pd.read_csv("VOCAB_SENT.csv", index_col="term_str")

In [27]:
SENT_COLS = VOCAB_SENT.columns.drop("n", errors="ignore")

BOW_SENT = BOW.join(VOCAB_SENT[SENT_COLS], on="term_str", how="inner")
BOW_SENT

                      n        tf       idf     tfidf  n_chars         p  \
mag_id term_str
0      abandonment    1  0.000064  3.321928  0.000212       11  0.000008
       abuse          1  0.000064  1.736966  0.000111        5  0.000023
       academic       1  0.000064  1.736966  0.000111        8  0.000023
       accolade       1  0.000064  3.321928  0.000212        8  0.000008
       accomplished   1  0.000064  1.736966  0.000111       12  0.000023
...                  ..       ...       ...       ...      ...       ...
9      winning        4  0.000329  1.000000  0.000329        7  0.000068
       wonderful      1  0.000082  0.736966  0.000061        9  0.000068
       words          3  0.000247  0.000000  0.000000        5  0.000197
       worn           1  0.000082  1.000000  0.000082        4  0.000038
       young         16  0.001317  0.000000  0.000000        5  0.000644

                             i max_pos max_pos_group  stop  ...  \
mag_id term_str                                             ...
0      abandonment   17.009610      NN            NN     0  ...
       abuse         15.424647      NN            NN     0  ...
       academic      15.424647      JJ            JJ     0  ...
       accolade      17.009610      NN            NN     0  ...
       accomplished  15.424647     VBN            VB     0  ...
...                        ...     ...           ...   ...  ...
9      winning       13.839685     VBG            NN     0  ...
       wonderful     13.839685      JJ            JJ     0  ...
       words         12.309170     NNS            NN     0  ...
       worn          14.687682     VBN            VB     0  ...
       young         10.600219      JJ            JJ     0  ...

                    nrc_anticipation  nrc_disgust  nrc_fear  nrc_joy  \
mag_id term_str
0      abandonment                 0            0         1        0
       abuse                       0            1         1        0
       academic                    0            0         0        0
       accolade                    1            0         0        1
       accomplished                0            0         0        1
...                              ...          ...       ...      ...
9      winning                     1            1         0        1
       wonderful                   0            0         0        1
       words                       0            0         0        0
       worn                        0            0         0        0
       young                       1            0         0        1

                     nrc_negative  nrc_positive  nrc_sadness  nrc_surprise  \
mag_id term_str
0      abandonment              1             0            1             1
       abuse                    1             0            1             0
       academic                 0             1            0             0
       accolade                 0             1            0             1
       accomplished             0             1            0             0
...                           ...           ...          ...           ...
9      winning                  0             1            1             1
       wonderful                0             1            0             1
       words                    1             0            0             0
       worn                     1             0            1             0
       young                    0             1            0             1

                     nrc_trust  nrc_sentiment
mag_id term_str
0      abandonment           0             -1
       abuse                 0             -1
       academic              1              1
       accolade              1              1
       accomplished          0              1
...                        ...            ...
9      winning               1              1
       wonderful             1              1
       words                 0             -1
       worn                  0             -1
       young                 0              1

[4268 rows x 22 columns]

In [28]:
BOW_SENT.shape

(4268, 22)

In [29]:
BOW_SENT.to_csv("BOW_SENT.csv")

### SENTIMENT DOC_SENT

In [30]:
BAG = ["mag_id"]

SENTIMENT_COLS = BOW_SENT.columns.drop(["n", "tf", "idf", "tfidf"], errors="ignore")

BAG_SENT = BOW_SENT[SENTIMENT_COLS].multiply(BOW_SENT["n"], axis=0)
BAG_SENT = BAG_SENT.groupby(BAG).sum()
BAG_SENT

,n_chars,p,i,max_pos,max_pos_group,stop,stem_porter,nrc_anger,nrc_anticipation,nrc_disgust,nrc_fear,nrc_joy,nrc_negative,nrc_positive,nrc_sadness,nrc_surprise,nrc_trust,nrc_sentiment
mag_id,,,,,,,,,,,,,,,,,,
0,7942,0.753994,14667.128801,NNNNJJNNVBNJJJJJJJJJJVBNVBNVBNVBNNNNNNNNSJJJJN...,NNNNJJNNVBJJJJJJJJJJVBVBVBVBNNNNNNNNNNNNNNNNNN...,21,abandonabusacademaccoladaccomplishaccreditaccu...,240,361,121,267,323,450,709,323,145,549,259
1,5885,0.507359,11473.044820,NNNNNNJJJJJJVBNVBNVBNNNNNNNNJJJJJJVBDVBDNNNNNN...,NNNNNNJJJJJJVBVBVBNNNNNNNNJJJJJJVBVBNNNNNNJJNN...,13,absencabsencaccidaccidentaccuraccuraccusaccusa...,150,258,94,237,220,386,513,261,93,410,127
2,6960,0.533490,13582.905630,VBNNNNNJJVBNNNNSJJJJVBVBNNJJJJNNPNNVBGJJNNNNNN...,VBNNNNJJVBNNNNJJJJVBVBNNJJJJNNNNVBJJNNNNNNNNNN...,10,abandonabortabsencaccurachievachievaddressadmi...,184,371,112,268,362,356,706,250,150,509,350
3,6702,0.451238,13353.491287,NNJJJJJJJJJJJJJJJJJJVBNNNNNSJJVBDJJJJJJJJNNNNJ...,NNJJJJJJJJJJJJJJJJJJVBNNNNJJVBJJJJJJJJNNNNJJNN...,17,abusacademaccuraccuraccuraccuraccuraccuraccura...,223,332,141,272,401,374,657,289,162,523,283
4,7008,0.654265,13831.358917,NNNNNNNNNNNNVBNJJVBNVBNVBNNNNNNSNNSJJJJNNVBGNN...,NNNNNNNNNNNNVBJJVBVBVBNNNNNNNNJJJJNNVBNNNNNNJJ...,16,abortabsenteabusaccidaccidaccidaccomplishaccur...,165,412,88,210,433,390,741,300,172,547,351
5,6443,0.553748,13370.312386,NNNNJJVBNVBNVBNVBNNNNNVBGNNNNNNJJNNNNVBGNNJJJJ...,NNNNJJVBVBVBVBNNNNVBNNNNNNJJNNNNVBNNJJJJNNNNNN...,9,abortabortaccuraccusaccusaccusaccusachievachie...,264,345,124,310,338,480,561,346,130,458,81
6,6588,0.602374,12723.087364,NNNNNNNNJJVBNNNNNJJVBDNNVBGNNNNNNNNNNRBNNNNNNN...,NNNNNNNNJJVBNNNNJJVBNNVBNNNNNNNNNNRBNNNNNNNNJJ...,7,absencaccidaccidaccidaccuraccusadvancadvancagg...,225,299,109,300,284,416,570,293,159,479,154
7,5742,0.426668,11681.693159,JJNNNNVBNJJJJJJVBNVBNJJNNVBDVBDVBDNNVBNJJNNPNN...,JJNNNNVBJJJJJJVBVBJJNNVBVBVBNNVBJJNNNNNNNNVBVB...,14,academaccidaccidaccomplishaccuraccuraccuraccus...,199,304,87,260,334,347,563,253,138,427,216
8,6616,0.546950,13200.363653,VBNNNNNNNNNJJVBNVBNVBNVBNVBNVBNVBNVBNNNNNJJVBD...,VBNNNNNNNNJJVBVBVBVBVBVBVBVBNNNNJJVBNNNNJJNNNN...,15,abandonabortabsencaccidaccidaccuraccusaccusacc...,269,305,166,319,295,491,546,322,132,452,55
9,6596,0.522850,13413.738969,NNNNNNJJJJJJVBNVBGVBGVBGVBJJJJNNNNJJVBDNNJJNNJ...,NNNNNNJJJJJJVBVBVBVBVBNNJJNNNNJJVBNNJJNNJJJJNN...,11,absencaccidaccidaccidentaccuraccuraccusaccusac...,264,342,120,354,341,443,600,325,152,479,157

In [31]:
BAG_SENT.to_csv("BAG_SENT.csv")

### SENTIMENT PLOT

In [39]:
# join sentiment w/ LIB metadata
LIB = pd.read_csv("data/LIB.csv", index_col="mag_id")

BAG_SENT_META = BAG_SENT.join(LIB[["month"]])
BAG_SENT_META

,n_chars,p,i,max_pos,max_pos_group,stop,stem_porter,nrc_anger,nrc_anticipation,nrc_disgust,nrc_fear,nrc_joy,nrc_negative,nrc_positive,nrc_sadness,nrc_surprise,nrc_trust,nrc_sentiment,month
mag_id,,,,,,,,,,,,,,,,,,,
0,7942,0.753994,14667.128801,NNNNJJNNVBNJJJJJJJJJJVBNVBNVBNVBNNNNNNNNSJJJJN...,NNNNJJNNVBJJJJJJJJJJVBVBVBVBNNNNNNNNNNNNNNNNNN...,21,abandonabusacademaccoladaccomplishaccreditaccu...,240,361,121,267,323,450,709,323,145,549,259,12
1,5885,0.507359,11473.044820,NNNNNNJJJJJJVBNVBNVBNNNNNNNNJJJJJJVBDVBDNNNNNN...,NNNNNNJJJJJJVBVBVBNNNNNNNNJJJJJJVBVBNNNNNNJJNN...,13,absencabsencaccidaccidentaccuraccuraccusaccusa...,150,258,94,237,220,386,513,261,93,410,127,5
2,6960,0.533490,13582.905630,VBNNNNNJJVBNNNNSJJJJVBVBNNJJJJNNPNNVBGJJNNNNNN...,VBNNNNJJVBNNNNJJJJVBVBNNJJJJNNNNVBJJNNNNNNNNNN...,10,abandonabortabsencaccurachievachievaddressadmi...,184,371,112,268,362,356,706,250,150,509,350,11
3,6702,0.451238,13353.491287,NNJJJJJJJJJJJJJJJJJJVBNNNNNSJJVBDJJJJJJJJNNNNJ...,NNJJJJJJJJJJJJJJJJJJVBNNNNJJVBJJJJJJJJNNNNJJNN...,17,abusacademaccuraccuraccuraccuraccuraccuraccura...,223,332,141,272,401,374,657,289,162,523,283,5
4,7008,0.654265,13831.358917,NNNNNNNNNNNNVBNJJVBNVBNVBNNNNNNSNNSJJJJNNVBGNN...,NNNNNNNNNNNNVBJJVBVBVBNNNNNNNNJJJJNNVBNNNNNNJJ...,16,abortabsenteabusaccidaccidaccidaccomplishaccur...,165,412,88,210,433,390,741,300,172,547,351,7
5,6443,0.553748,13370.312386,NNNNJJVBNVBNVBNVBNNNNNVBGNNNNNNJJNNNNVBGNNJJJJ...,NNNNJJVBVBVBVBNNNNVBNNNNNNJJNNNNVBNNJJJJNNNNNN...,9,abortabortaccuraccusaccusaccusaccusachievachie...,264,345,124,310,338,480,561,346,130,458,81,11
6,6588,0.602374,12723.087364,NNNNNNNNJJVBNNNNNJJVBDNNVBGNNNNNNNNNNRBNNNNNNN...,NNNNNNNNJJVBNNNNJJVBNNVBNNNNNNNNNNRBNNNNNNNNJJ...,7,absencaccidaccidaccidaccuraccusadvancadvancagg...,225,299,109,300,284,416,570,293,159,479,154,3
7,5742,0.426668,11681.693159,JJNNNNVBNJJJJJJVBNVBNJJNNVBDVBDVBDNNVBNJJNNPNN...,JJNNNNVBJJJJJJVBVBJJNNVBVBVBNNVBJJNNNNNNNNVBVB...,14,academaccidaccidaccomplishaccuraccuraccuraccus...,199,304,87,260,334,347,563,253,138,427,216,2
8,6616,0.546950,13200.363653,VBNNNNNNNNNJJVBNVBNVBNVBNVBNVBNVBNVBNNNNNJJVBD...,VBNNNNNNNNJJVBVBVBVBVBVBVBVBNNNNJJVBNNNNJJNNNN...,15,abandonabortabsencaccidaccidaccuraccusaccusacc...,269,305,166,319,295,491,546,322,132,452,55,8
9,6596,0.522850,13413.738969,NNNNNNJJJJJJVBNVBGVBGVBGVBJJJJNNNNJJVBDNNJJNNJ...,NNNNNNJJJJJJVBVBVBVBVBNNJJNNNNJJVBNNJJNNJJJJNN...,11,absencaccidaccidaccidentaccuraccuraccusaccusac...,264,342,120,354,341,443,600,325,152,479,157,4

In [40]:
# average sentiment by quarter
SENT_BY_MONTH = BAG_SENT_META.groupby("month").mean(numeric_only=True)
SENT_BY_MONTH

,n_chars,p,i,stop,nrc_anger,nrc_anticipation,nrc_disgust,nrc_fear,nrc_joy,nrc_negative,nrc_positive,nrc_sadness,nrc_surprise,nrc_trust,nrc_sentiment
month,,,,,,,,,,,,,,,
2,5742.0,0.426668,11681.693159,14.0,199.0,304.0,87.0,260.0,334.0,347.0,563.0,253.0,138.0,427.0,216.0
3,6588.0,0.602374,12723.087364,7.0,225.0,299.0,109.0,300.0,284.0,416.0,570.0,293.0,159.0,479.0,154.0
4,6596.0,0.522850,13413.738969,11.0,264.0,342.0,120.0,354.0,341.0,443.0,600.0,325.0,152.0,479.0,157.0
5,6293.5,0.479299,12413.268053,15.0,186.5,295.0,117.5,254.5,310.5,380.0,585.0,275.0,127.5,466.5,205.0
7,7008.0,0.654265,13831.358917,16.0,165.0,412.0,88.0,210.0,433.0,390.0,741.0,300.0,172.0,547.0,351.0
8,6616.0,0.546950,13200.363653,15.0,269.0,305.0,166.0,319.0,295.0,491.0,546.0,322.0,132.0,452.0,55.0
11,6701.5,0.543619,13476.609008,9.5,224.0,358.0,118.0,289.0,350.0,418.0,633.5,298.0,140.0,483.5,215.5
12,7942.0,0.753994,14667.128801,21.0,240.0,361.0,121.0,267.0,323.0,450.0,709.0,323.0,145.0,549.0,259.0

In [41]:
SENT_BY_MONTH_PLOT = SENT_BY_MONTH.reset_index()

px.line(SENT_BY_MONTH_PLOT,
        x="month",
        y=SENT_BY_MONTH.columns,
        markers=True,
        title="Sentiment Over Time by Month",
        height=700)