In [11]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import normalize

In [12]:
TFIDF = pd.read_csv("TFIDF.csv", index_col="mag_id")
TFIDF

,aa,aaf,aaron,ababa,abandoned,abandonment,abbott,abc,abclou,abcparamount,...,zoomed,zooming,zoot,zor,zs,zumwalt,zunicia,zuniga,zurich,zw
mag_id,,,,,,,,,,,,,,,,,,,,,
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000212,0.000000,0.000064,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000212,0.000212,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.000000,0.000111,0.000000,0.000000,0.000000,0.000000,0.000084,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000165,0.000000,0.000236,0.000142,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000236
3,0.000483,0.000241,0.000000,0.000000,0.000000,0.000000,0.000000,0.000509,0.00000,0.000000,...,0.000000,0.000241,0.000000,0.000000,0.000000,0.000000,0.000241,0.000483,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000345,0.00023,0.000000,...,0.000000,0.000000,0.000459,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000252,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000321,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000269,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000214,0.000000
7,0.000000,0.000000,0.000662,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000110,0.000000
8,0.000000,0.000000,0.000107,0.000000,0.000188,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000268,0.000000,0.000000,0.000268,0.000000,0.000000,0.000000,0.000000,0.000107,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000109,0.000000

In [13]:
# Reduce features by keeping words with total TFIDF above 0
SIG_WORDS = TFIDF.sum().sort_values(ascending=False)
SIG_WORDS = SIG_WORDS[SIG_WORDS > 0].index
SIG_WORDS

Index(['blacks', 'negroes', 'tito', 'mink', 'granada', 'diggs', 'ali',
       'benson', 'ruby', 'reggie',
       ...
       'moneta', 'sleet', 'oldest', 'sutton', 'basil', 'photos', 'perhaps',
       'maurice', 'fentress', 'confidential'],
      dtype='object', length=15770)

In [14]:
TFIDF_REDUCED = TFIDF[SIG_WORDS]
TFIDF_REDUCED

,blacks,negroes,tito,mink,granada,diggs,ali,benson,ruby,reggie,...,moneta,sleet,oldest,sutton,basil,photos,perhaps,maurice,fentress,confidential
mag_id,,,,,,,,,,,,,,,,,,,,,
0,0.004216,0.000000,0.000000,0.000000,0.000000,0.000255,0.000702,0.000000,0.000000,0.000000,...,0.000019,0.000019,0.000010,0.000010,0.000019,0.000010,0.000010,0.000010,0.000010,0.000010
1,0.000000,0.000864,0.000000,0.000000,0.000000,0.003611,0.000756,0.000000,0.000000,0.000000,...,0.000013,0.000013,0.000013,0.000013,0.000026,0.000013,0.000000,0.000013,0.000013,0.000013
2,0.001411,0.000000,0.004460,0.000000,0.004253,0.000000,0.001067,0.000094,0.000000,0.000000,...,0.000011,0.000011,0.000000,0.000022,0.000011,0.000011,0.000022,0.000011,0.000011,0.000011
3,0.001537,0.000037,0.000000,0.000000,0.000000,0.000000,0.000509,0.000288,0.000288,0.003038,...,0.000011,0.000011,0.000011,0.000011,0.000011,0.000011,0.000022,0.000011,0.000011,0.000011
4,0.001096,0.000000,0.000000,0.000000,0.000000,0.000207,0.001036,0.003471,0.000091,0.000321,...,0.000032,0.000032,0.000011,0.000011,0.000011,0.000021,0.000011,0.000011,0.000011,0.000011
5,0.000000,0.001286,0.000000,0.004078,0.000000,0.000000,0.000000,0.000000,0.000200,0.000000,...,0.000000,0.000000,0.000023,0.000000,0.000000,0.000012,0.000012,0.000012,0.000000,0.000000
6,0.000000,0.000791,0.000000,0.000000,0.000000,0.000081,0.000000,0.000000,0.000000,0.000000,...,0.000012,0.000012,0.000012,0.000012,0.000012,0.000000,0.000012,0.000012,0.000012,0.000012
7,0.000000,0.000515,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.003087,0.000000,...,0.000013,0.000013,0.000025,0.000025,0.000013,0.000013,0.000013,0.000000,0.000013,0.000013
8,0.000000,0.001164,0.000000,0.000140,0.000000,0.000081,0.000000,0.000107,0.000000,0.000000,...,0.000012,0.000012,0.000012,0.000012,0.000012,0.000012,0.000012,0.000012,0.000012,0.000012
9,0.000000,0.000466,0.000191,0.000143,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000013,0.000013,0.000013,0.000013,0.000013,0.000025,0.000013,0.000025,0.000013,0.000013

In [15]:
# L2 normalize
TFIDF_L2 = pd.DataFrame(
    normalize(TFIDF_REDUCED, norm='l2'),
    index=TFIDF_REDUCED.index,
    columns=TFIDF_REDUCED.columns)

TFIDF_L2

,blacks,negroes,tito,mink,granada,diggs,ali,benson,ruby,reggie,...,moneta,sleet,oldest,sutton,basil,photos,perhaps,maurice,fentress,confidential
mag_id,,,,,,,,,,,,,,,,,,,,,
0,0.299832,0.000000,0.000000,0.000000,0.000000,0.018145,0.049899,0.000000,0.000000,0.000000,...,0.001379,0.001379,0.000690,0.000690,0.001379,0.000690,0.000690,0.000690,0.000690,0.000690
1,0.000000,0.059798,0.000000,0.000000,0.000000,0.249848,0.052294,0.000000,0.000000,0.000000,...,0.000883,0.000883,0.000883,0.000883,0.001766,0.000883,0.000000,0.000883,0.000883,0.000883
2,0.089170,0.000000,0.281924,0.000000,0.268895,0.000000,0.067455,0.005945,0.000000,0.000000,...,0.000684,0.000684,0.000000,0.001367,0.000684,0.000684,0.001367,0.000684,0.000684,0.000684
3,0.106139,0.002582,0.000000,0.000000,0.000000,0.000000,0.035127,0.019901,0.019901,0.209734,...,0.000763,0.000763,0.000763,0.000763,0.000763,0.000763,0.001526,0.000763,0.000763,0.000763
4,0.079359,0.000000,0.000000,0.000000,0.000000,0.015008,0.075041,0.251304,0.006613,0.023232,...,0.002281,0.002281,0.000760,0.000760,0.000760,0.001521,0.000760,0.000760,0.000760,0.000760
5,0.000000,0.083483,0.000000,0.264723,0.000000,0.000000,0.000000,0.000000,0.012998,0.000000,...,0.000000,0.000000,0.001495,0.000000,0.000000,0.000747,0.000747,0.000747,0.000000,0.000000
6,0.000000,0.058463,0.000000,0.000000,0.000000,0.005980,0.000000,0.000000,0.000000,0.000000,...,0.000909,0.000909,0.000909,0.000909,0.000909,0.000000,0.000909,0.000909,0.000909,0.000909
7,0.000000,0.036335,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.217804,0.000000,...,0.000894,0.000894,0.001789,0.001789,0.000894,0.000894,0.000894,0.000000,0.000894,0.000894
8,0.000000,0.084661,0.000000,0.010206,0.000000,0.005876,0.000000,0.007768,0.000000,0.000000,...,0.000893,0.000893,0.000893,0.000893,0.000893,0.000893,0.000893,0.000893,0.000893,0.000893
9,0.000000,0.033191,0.013615,0.010185,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000891,0.000891,0.000891,0.000891,0.000891,0.001783,0.000891,0.001783,0.000891,0.000891

In [16]:
TFIDF_L2.to_csv('TFIDF_L2.csv')